text_data:
  train: 60000
  validation: 785
  test: 1000

qa_data:
  train: 98000
  validation: 1025
  test: 10000

dpo_data: 
  train:
  validation:
  test:

instruction_data:
  train:
  validation:
  test:

iam_data:
  train:
  validation:
  test:
  